#!/usr/bin/env python3
"""gen-lane-pages.py — src/data/lane-pages.json (the per-case records behind /model/<model>/ and
/provider/<repo>/) generated from amber.db. Never edit that file by hand.

    python3 scripts/gen-lane-pages.py            # regenerate and write src/data/lane-pages.json
    python3 scripts/gen-lane-pages.py --check    # regenerate in memory, fail if the file differs

Read-only against amber.db (connect(write=False)); it reuses publish.py and export_site_data.py from
the amber-run workspace (the directory AMBER_REPO_ROOT points to, required) so every number is the board's number. The output goes through the same redline scan as
site-data.json (private values and internal markers abort the run).

Order of work after an exam sitting is imported:
    sync_site.py --site <this checkout> --write     # axes.json, site-data.json  (amber-run workspace)
    python3 scripts/gen-lane-pages.py               # this file
    python3 scripts/gen-lane-pages.py --check       # must print "ok"
The build already refuses to run when a lane's total or case count here differs from axes.json, so a
score change cannot reach the site without regenerating this file; --check also catches changes that
leave the total alone (for example a case that flips from fail to NA).

Policy that lives in this generator (versioned code, like HOLDS_V1 in publish.py), each owner-approved:
    SKIP_LANES        lanes without pages (crof, frozen; owner 2026-10-03)
    CONV_ALIAS        public alias of the convergence case (scope_papers still holds the internal id;
                      value from the amber-run workspace, tools/amberdb/import.py CONV_PAPER)
    history           only the all-lane hold (publish.py CASE_HOLDS_V2) is applied to sittings other than
                      the one on the board; registered per-lane holds belong to the board's sitting
    history_withheld  lanes whose board sitting is not the latest headline (pinned or composed baselines)
                      show no sitting history until the owner words it
"""
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "data", "lane-pages.json")
AXES = os.path.join(ROOT, "src", "data", "axes.json")
if not os.environ.get("AMBER_REPO_ROOT"):
    sys.exit("set AMBER_REPO_ROOT to the amber-run workspace first (without it the tools read an old database)")
DB_HOME = os.path.abspath(os.path.expanduser(os.environ["AMBER_REPO_ROOT"]))
os.environ["AMBER_REPO_ROOT"] = DB_HOME      # tools/amberdb reads its DB path from this variable
sys.path.insert(0, os.path.join(DB_HOME, "tools", "amberdb"))
import db as A  # noqa: E402
import export_site_data as X  # noqa: E402
import publish as P  # noqa: E402

SCHEMA = "lane-pages-v1"
SKIP_LANES = {"crof"}
CONV_CASE, CONV_ALIAS = "CONV-001", "A-3f2a9cdd"
GIT = ["env", "GIT_CONFIG_NOSYSTEM=1", "GIT_CONFIG_GLOBAL=/dev/null", "git",
       "-c", "core.fsmonitor=", "-c", "core.hooksPath=/dev/null", "-C", DB_HOME]


def git(*args):
    return subprocess.run(GIT + list(args), capture_output=True, text=True).stdout.strip()


def source_info():
    with open(A.DB_PATH, "rb") as fh:
        db_sha = hashlib.sha256(fh.read()).hexdigest()
    return {
        "amber_db_sha256": db_sha,
        "amber_db_blob": git("rev-parse", "HEAD:amber.db"),
        "amber_run_commit": git("rev-parse", "HEAD"),
        "tools_or_db_uncommitted": bool(git("status", "--porcelain", "--", "amber.db", "tools/amberdb")),
        "note": "generated by scripts/gen-lane-pages.py from amber.db; do not edit by hand",
    }


def tokens_of(board, attempt_id, unreported):
    total = 0
    for u in board.con.execute("select tok_in, tok_cache_read, tok_cache_write, tok_out from attempt_usage where attempt_id=?",
                               (attempt_id,)):
        total += sum((u[k] or 0) for k in ("tok_in", "tok_cache_read", "tok_cache_write", "tok_out") if k not in unreported)
    return total or None


def model_slug(model):
    return re.sub(r"[^a-z0-9.]+", "-", model.split("/")[-1].lower()).strip("-")


def build(con):
    board = P.Board(con)
    alias = {}
    for rows in board.sp.values():
        for p in rows:
            public = CONV_ALIAS if p["case_alias"] == CONV_CASE else p["public_alias"]
            alias.setdefault(p["case_alias"], (public, p["axis"]))
    axis_ids = {a["id"] for a in X.taxonomy(con)[1]}
    lanes = {}
    for lane in board.lanes:
        pid = lane["public_id"]
        if pid in SKIP_LANES:
            continue
        lr = board.combined_lane(lane) or board.compute_lane(lane)
        unreported = {c for c in (lane["unreported_cols"] or "").split(",") if c}
        cases = []
        for case in lr["order"]:
            status = lr["results"][case]
            attempt = X.attempt_for(board, lr, case)
            cases.append({
                "alias": alias[case][0], "axis": alias[case][1],
                "status": "pass" if status == "pass" else "fail" if status == "fail" else "na",
                "wall_s": round(attempt["wall_s"]) if attempt and attempt["wall_s"] is not None else None,
                "tokens": tokens_of(board, attempt["id"], unreported) if attempt else None,
            })
        latest = board.headline_of(lane["id"])
        comp = lr.get("combine")
        shown_run = (comp["baseline"]["run_dir"] if comp and comp.get("baseline", {}).get("run_dir")
                     else lr["sitting"]["run_dir"])
        history = []
        for h in sorted((h for h in board.headlines if h["lane_id"] == lane["id"]),
                        key=lambda h: (h["week"], h["first_started_at"] or h["run_dir"])):
            results = board._results_of(h["id"], board.scope_for(h["week"]))
            if h["run_dir"] == shown_run:
                P.apply_holds(pid, results)
            else:
                for held_case, hold in P.CASE_HOLDS_V2.items():
                    if held_case in results and results[held_case] != "pass":
                        results[held_case] = "NA:" + hold["na_reason"]
            values = list(results.values())
            row = {"week": h["week"], "total": sum(v == "pass" for v in values),
                   "na": sum(v not in ("pass", "fail") for v in values), "n": len(values),
                   "current": h["run_dir"] == shown_run}
            if row["current"]:
                row.update(total=lr["total"], na=lr["na"], n=lr["n"])
            history.append(row)
        lanes[pid] = {
            "id": pid, "name": lane["public_name"], "model": lane["model"], "vendor": lane["vendor"],
            "repo": lane["repo"], "provider_slug": lane["repo"].removeprefix("amber-"),
            "model_slug": model_slug(lane["model"]), "band": lane["band"], "week": P.lane_week(lr),
            "frozen_week": lane["frozen_week"], "total": lr["total"], "na": lr["na"], "n": lr["n"],
            "cases": cases, "history": history,
            "history_withheld": shown_run != latest["run_dir"], "composed": bool(comp),
            "_axis_check": {k: [v["p"], v["n"], v["na"]] for k, v in lr["axis"].items() if k in axis_ids},
        }
    slugs = {}
    for lane in lanes.values():
        slugs.setdefault(lane["model_slug"], set()).add(lane["model"].split("/")[-1].lower())
    assert all(len(names) == 1 for names in slugs.values()), f"two model names share a slug: {slugs}"
    return {"schema": SCHEMA, "rule_version": A.RULE_VERSION, "skipped_lanes": sorted(SKIP_LANES), "lanes": lanes}


def against_site_axes(doc):
    """The published axes.json must describe the same lanes: otherwise sync_site.py --write is still pending."""
    published = {lane["id"]: lane for lane in json.load(open(AXES, encoding="utf-8"))}
    errors = []
    for pid, lane in doc["lanes"].items():
        site = published.get(pid)
        if site is None:
            errors.append(f"{pid}: not in src/data/axes.json")
            continue
        cells = {k: [v["p"], v["n"], v.get("na", 0)] for k, v in site["axis"].items() if v["n"] > 0}
        mine = {k: v for k, v in lane["_axis_check"].items() if v[1] > 0}
        if (lane["total"], lane["n"], mine) != (site["total"], site["n"], cells):
            errors.append(f"{pid}: total/n/axes differ from src/data/axes.json (run sync_site.py --write first?)")
    return errors


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="compare with the file on disk; write nothing")
    args = ap.parse_args()
    con = A.connect(A.DB_PATH, write=False)
    doc = build(con)
    errors = against_site_axes(doc)
    for lane in doc["lanes"].values():
        lane.pop("_axis_check")
    hits = X.redline(con, doc)
    if hits:
        print("gen-lane-pages aborted (redline):", *hits[:20], sep="\n    ")
        return 1
    if errors:
        print("gen-lane-pages aborted:", *errors, sep="\n    ")
        return 1
    doc["source"] = source_info()
    text = json.dumps(doc, ensure_ascii=False, indent=1, sort_keys=True) + "\n"
    if not args.check:
        with open(OUT + ".tmp", "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(OUT + ".tmp", OUT)
        print(f"gen-lane-pages: wrote {len(doc['lanes'])} lanes to src/data/lane-pages.json "
              f"(amber-run@{doc['source']['amber_run_commit'][:8]})")
        return 0
    if not os.path.exists(OUT):
        print("gen-lane-pages --check: src/data/lane-pages.json is missing")
        return 1
    current = json.load(open(OUT, encoding="utf-8"))
    differing = sorted(pid for pid in set(current["lanes"]) | set(doc["lanes"])
                       if current["lanes"].get(pid) != doc["lanes"].get(pid))
    if differing or current.get("rule_version") != doc["rule_version"] or current.get("schema") != doc["schema"]:
        print("gen-lane-pages --check FAILED: src/data/lane-pages.json differs from amber.db for:",
              ", ".join(differing) or "(header only)")
        print("    regenerate with: python3 scripts/gen-lane-pages.py")
        return 1
    note = "" if current.get("source") == doc["source"] else " (source info differs: db or tools commit moved, lanes identical)"
    print(f"gen-lane-pages --check: ok, {len(doc['lanes'])} lanes equal amber.db{note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
